# Generated by Django 4.2.1 on 2023-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_create_card_checkoutcart_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_Card',
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='product',
        ),
        migrations.AddField(
            model_name='checkoutcart',
            name='product',
            field=models.ManyToManyField(null=True, related_name='checkout_cart', to='ecom_app.product'),
        ),
    ]
