# Generated by Django 4.2.1 on 2023-08-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_delete_create_card_remove_checkoutcart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='checkoutcart',
            name='item',
            field=models.ManyToManyField(null=True, related_name='checkout_cart', to='ecom_app.cartitem'),
        ),
    ]
